# Generated by Django 6.0 on 2026-04-23 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('submission', '0004_submission_problem_user_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'create_time'], name='message_recipient_time_idx'),
        ),
    ]
