# Generated by Django 5.2.3 on 2025-09-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='class_name',
            field=models.TextField(null=True),
        ),
    ]
