# Generated by Django 5.2.3 on 2025-09-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='class_name',
        ),
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.TextField(null=True),
        ),
    ]
