# Generated by Django 6.0.4 on 2026-05-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_remove_userprofile_class_name_user_class_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="admin_type",
            field=models.TextField(choices=[("Regular User", "Regular User"), ("Admin", "Admin"), ("Super Admin", "Super Admin")], default="Regular User"),
        ),
        migrations.AlterField(
            model_name="user",
            name="problem_permission",
            field=models.TextField(choices=[("None", "None"), ("Own", "Own"), ("All", "All")], default="None"),
        ),
    ]
