# Generated by Django 6.0.4 on 2026-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_admin_type_alter_user_problem_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='open_api',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_keys',
            field=models.JSONField(db_default=models.Value([]), default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_auth',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accepted_number',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acm_problems_status',
            field=models.JSONField(db_default=models.Value({}), default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oi_problems_status',
            field=models.JSONField(db_default=models.Value({}), default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='submission_number',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_score',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
    ]
