# Generated by Django 6.0.4 on 2026-07-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_admin_to_student_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='oi_problems_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_score',
        ),
    ]
