# Generated by Django 6.0.4 on 2026-08-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_userprofile_oi_problems_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tfa_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_auth',
        ),
    ]
