# Generated by Django 6.0.4 on 2026-08-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_tfa_token_remove_user_two_factor_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token_expire_time',
        ),
    ]
