# Generated by Django 5.0.6 on 2025-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_session_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='明文密码'),
        ),
    ]
