# Generated by Django 5.0.6 on 2024-06-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_migrate_languages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysoptions',
            name='value',
            field=models.JSONField(),
        ),
    ]
