# Generated by Django 5.2.3 on 2025-09-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        ('problem', '0001_initial'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user_id', 'create_time'], name='user_create_time_idx'),
        ),
    ]
