# Generated by Django 6.0 on 2026-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        ('problem', '0005_remove_spj_fields'),
        ('submission', '0002_submission_user_create_time_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest_id', '-create_time'], name='contest_create_time_idx'),
        ),
    ]
