# Generated by Django 6.0 on 2026-04-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_acmcontestrank_acm_rank_contest_user_idx_and_more'),
        ('problem', '0007_problem_problem_visible_idx'),
        ('submission', '0003_add_contest_create_time_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem_id', 'user_id'], name='problem_user_idx'),
        ),
    ]
