# Generated by Django 5.0.6 on 2024-06-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20180501_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tag',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
