# Generated by Django 5.0.6 on 2024-06-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0004_announcement_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ("-top", "-create_time")},
        ),
        migrations.AddField(
            model_name="announcement",
            name="top",
            field=models.BooleanField(default=False),
        ),
    ]
