# Generated by Django 5.0.6 on 2024-06-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
