# Generated by Django 6.0 on 2026-03-30 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='acmcontestrank',
            index=models.Index(fields=['contest', 'accepted_number', 'total_time'], name='acm_rank_order_idx'),
        ),
        migrations.AddIndex(
            model_name='oicontestrank',
            index=models.Index(fields=['contest', 'total_score'], name='oi_rank_order_idx'),
        ),
    ]
