# Generated by Django 6.0 on 2026-04-23 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_acmcontestrank_acm_rank_order_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='acmcontestrank',
            index=models.Index(fields=['contest', 'user'], name='acm_rank_contest_user_idx'),
        ),
        migrations.AddIndex(
            model_name='oicontestrank',
            index=models.Index(fields=['contest', 'user'], name='oi_rank_contest_user_idx'),
        ),
    ]
