# Generated by Django 6.0.4 on 2026-05-09 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0003_acmcontestrank_acm_rank_contest_user_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="acmcontestrank",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="oicontestrank",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="contest",
            name="rule_type",
            field=models.TextField(choices=[("ACM", "ACM"), ("OI", "OI")]),
        ),
        migrations.AddConstraint(
            model_name="acmcontestrank",
            constraint=models.UniqueConstraint(fields=("user", "contest"), name="unique_acm_rank_user_contest"),
        ),
        migrations.AddConstraint(
            model_name="oicontestrank",
            constraint=models.UniqueConstraint(fields=("user", "contest"), name="unique_oi_rank_user_contest"),
        ),
    ]
