# Generated by Django 6.0.4 on 2026-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_alter_acmcontestrank_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmcontestrank',
            name='accepted_number',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='acmcontestrank',
            name='submission_info',
            field=models.JSONField(db_default=models.Value({}), default=dict),
        ),
        migrations.AlterField(
            model_name='acmcontestrank',
            name='submission_number',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='acmcontestrank',
            name='total_time',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='oicontestrank',
            name='submission_info',
            field=models.JSONField(db_default=models.Value({}), default=dict),
        ),
        migrations.AlterField(
            model_name='oicontestrank',
            name='submission_number',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='oicontestrank',
            name='total_score',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
