# Generated by Django 5.0.6 on 2024-07-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_alter_acmcontestrank_submission_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='tag',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
