# Generated by Django 5.2.3 on 2025-06-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='type',
            field=models.CharField(choices=[('python', 'Python'), ('c', 'C')], default='python', max_length=10),
        ),
    ]
