# Generated by Django 5.2.3 on 2025-06-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_tutorial_code_tutorial_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
