# Generated by Django 6.0 on 2026-04-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('mcq', '选择题'), ('sort', '代码排序'), ('fill', '代码填空')], max_length=16),
        ),
    ]
