# Generated by Django 6.0.4 on 2026-06-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_migrate_mcq_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('mcq', '选择题'), ('sort', '代码排序'), ('fill', '代码填空'), ('match', '连线匹配'), ('predict', '输出预测'), ('debug', '代码找错'), ('group', '归类分组')], max_length=16),
        ),
    ]
