# Generated by Django 6.0 on 2026-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchartsubmission',
            name='ai_model',
            field=models.CharField(default='deepseek-v4-flash', max_length=50),
        ),
    ]
