# Generated by Django 5.2.3 on 2025-10-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='is_public',
        ),
    ]
