# Generated by Django 5.2.3 on 2025-10-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0002_remove_is_public_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemsetbadge',
            name='level',
        ),
    ]
