# Generated by Django 5.2.3 on 2025-10-23 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_remove_spj_fields'),
        ('problemset', '0004_alter_problemset_status_problemsetsubmission'),
        ('submission', '0002_submission_user_create_time_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemsetsubmission',
            options={'ordering': ('-submission__create_time',), 'verbose_name': '题单提交记录', 'verbose_name_plural': '题单提交记录'},
        ),
        migrations.RemoveIndex(
            model_name='problemsetsubmission',
            name='problemset__user_id_63c1d0_idx',
        ),
        migrations.RemoveField(
            model_name='problemsetsubmission',
            name='code_length',
        ),
        migrations.RemoveField(
            model_name='problemsetsubmission',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='problemsetsubmission',
            name='language',
        ),
        migrations.RemoveField(
            model_name='problemsetsubmission',
            name='memory_usage',
        ),
        migrations.RemoveField(
            model_name='problemsetsubmission',
            name='result',
        ),
        migrations.RemoveField(
            model_name='problemsetsubmission',
            name='score',
        ),
        migrations.RemoveField(
            model_name='problemsetsubmission',
            name='submit_time',
        ),
        migrations.AddIndex(
            model_name='problemsetsubmission',
            index=models.Index(fields=['user'], name='problemset__user_id_2f1501_idx'),
        ),
    ]
