# Generated by Django 5.2.3 on 2025-10-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0005_alter_problemsetsubmission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='is_displayed',
        ),
    ]
