# Generated by Django 6.0 on 2026-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_remove_is_displayed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
    ]
