# Generated by Django 5.2.3 on 2025-10-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='prompt',
            field=models.TextField(null=True),
        ),
    ]
