# Generated by Django 5.2.3 on 2025-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answers',
            field=models.JSONField(null=True),
        ),
    ]
