# Generated by Django 5.2.3 on 2025-10-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_problem_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='allow_flowchart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='flowchart_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='problem',
            name='flowchart_hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='mermaid_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='show_flowchart',
            field=models.BooleanField(default=False),
        ),
    ]
