# Generated by Django 5.2.3 on 2025-10-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_problem_allow_flowchart_problem_flowchart_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='spj',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='spj_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='spj_compile_ok',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='spj_language',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='spj_version',
        ),
    ]
