# Generated by Django 6.0 on 2026-03-30 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_acmcontestrank_acm_rank_order_idx_and_more'),
        ('problem', '0005_remove_spj_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['contest', 'visible'], name='problem_contest_visible_idx'),
        ),
    ]
