# Generated by Django 6.0.4 on 2026-05-09 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0004_alter_acmcontestrank_unique_together_and_more"),
        ("problem", "0007_problem_problem_visible_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="problem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.TextField(choices=[("Low", "Low"), ("Mid", "Mid"), ("High", "High")]),
        ),
        migrations.AlterField(
            model_name="problem",
            name="rule_type",
            field=models.TextField(choices=[("ACM", "ACM"), ("OI", "OI")]),
        ),
        migrations.AddConstraint(
            model_name="problem",
            constraint=models.UniqueConstraint(fields=("_id", "contest"), name="unique_problem_id_contest"),
        ),
    ]
