# Generated by Django 6.0.4 on 2026-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_alter_problem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='accepted_number',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='allow_flowchart',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='flowchart_data',
            field=models.JSONField(db_default=models.Value({}), default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_public',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='share_submission',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='show_flowchart',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statistic_info',
            field=models.JSONField(db_default=models.Value({}), default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='submission_number',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='total_score',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='visible',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
