# Generated by Django 6.0.4 on 2026-05-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_alter_problem_accepted_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ast_rules',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
