# Generated by Django 6.0.4 on 2026-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_problem_ast_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sql_config',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
