# Generated by Django 6.0.4 on 2026-07-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_problem_sql_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sql_display',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
