# Generated by Django 6.0.4 on 2026-07-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_problem_sql_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='io_mode',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='rule_type',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='total_score',
        ),
    ]
