# Generated by Django 5.0.6 on 2025-04-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_alter_problem_io_mode_alter_problem_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
