# Generated by Django 5.0.6 on 2025-05-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_alter_problem_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
