# Generated by Django 5.2.3 on 2025-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='model',
            field=models.TextField(default='deepseek-chat'),
        ),
    ]
