# Generated by Django 6.0 on 2026-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aianalysis_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='model',
            field=models.TextField(default='deepseek-v4-flash'),
        ),
    ]
