# Generated by Django 6.0.4 on 2026-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_aianalysis_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
