# Generated by Django 5.0.6 on 2024-06-29 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0015_alter_problem_io_mode_alter_problem_languages_and_more'),
        ('submission', '0013_alter_submission_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='Python', choices=[('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Java', 'Java')], max_length=10, verbose_name='解决这道题使用的语言')),
                ('description_rating', models.PositiveSmallIntegerField(default=5, verbose_name='题目描述的分数')),
                ('difficulty_rating', models.PositiveSmallIntegerField(default=5, verbose_name='题目难度的分数')),
                ('comprehensive_rating', models.PositiveSmallIntegerField(default=5, verbose_name='综合的分数')),
                ('content', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
                'ordering': ('-create_time',),
            },
        ),
    ]
