# Generated by Django 5.0.6 on 2024-06-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-create_time',)},
        ),
    ]
