# Generated by Django 6.0 on 2026-04-23 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('problem', '0007_problem_problem_visible_idx'),
        ('submission', '0004_submission_problem_user_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['problem', 'create_time'], name='comment_problem_time_idx'),
        ),
    ]
