# Generated by Django 5.0.6 on 2024-06-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_options'),
        ('submission', '0013_alter_submission_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='problem_solved',
        ),
        migrations.AlterField(
            model_name='comment',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Java', 'Java')], default='Python', max_length=10, verbose_name='解决这道题使用的语言'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='submission.submission'),
            preserve_default=False,
        ),
    ]
