# Generated by Django 6.0.4 on 2026-08-06 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0014_problem_tag_ci_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('too_easy', '太简单'), ('too_hard', '太难了'), ('confusing', '没看懂'), ('buggy', '题目有错'), ('learned', '学到了'), ('interesting', '有意思'), ('want_explain', '想听讲解')], max_length=20, verbose_name='表情类型')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reaction',
                'indexes': [models.Index(fields=['problem', 'type'], name='reaction_problem_type_idx')],
                'unique_together': {('problem', 'user', 'type')},
            },
        ),
    ]
